include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - file_names
    - package_api_docs
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_null_aware_assignments
    - unnecessary_statements

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
